name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [default, fastapi-react, fullstack-js, npm-package, svelte, renovate]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Validate ${{ matrix.task }}.json
        run: npx --yes --package renovate --strict -- renovate-config-validator ${{ matrix.task }}.json
